//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternalDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.PaymentHistories = new HashSet<PaymentHistory>();
        }
    
        public int Id { get; set; }
        public int ProductTypeId { get; set; }
        public bool IsActive { get; set; }
        public string Name { get; set; }
        public string Display { get; set; }
        public decimal Value { get; set; }
        public string Currency { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedAt { get; set; }
    
        public virtual ICollection<PaymentHistory> PaymentHistories { get; set; }
        public virtual ProductType ProductType { get; set; }
    }
}
