//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternalDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriptionPlan
    {
        public SubscriptionPlan()
        {
            this.PersonalDetails = new HashSet<PersonalDetail>();
        }
    
        public int Id { get; set; }
        public bool UnlimitedAccess { get; set; }
        public Nullable<System.DateTime> ActiveUntil { get; set; }
        public int Credits { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedAt { get; set; }
    
        public virtual ICollection<PersonalDetail> PersonalDetails { get; set; }
    }
}
